name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Imprimir en consola
        run: echo "Hello World, Github Actions"

  test:
    needs: helloworld
    runs-on: ubuntu-latest
    env:
      # Secrets (asegúrate que existen exactamente con estos nombres)
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      USER_COLLECTION: ${{ secrets.USER_COLLECTION }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Firebase credentials to file (if provided)
        if: ${{ env.FIREBASE_CREDENTIALS_BASE64 != '' }}
        run: |
          echo "$FIREBASE_CREDENTIALS_BASE64" | base64 --decode > ./firebase_credentials.json
          echo "FIREBASE_CRED_PATH=$(pwd)/firebase_credentials.json" >> $GITHUB_ENV

      - name: Debug env presence (opcional)
        run: |
          python - <<'PY'
          import os
          keys = ["DATABASE_NAME","MONGODB_URI","FIREBASE_CREDENTIALS_BASE64","FIREBASE_CRED_PATH","RAILWAY_TOKEN"]
          for k in keys:
              print(k, "->", bool(os.environ.get(k)))
          PY

      - name: Test FastApi imports
        run: |
          python -c "from main import app; print('FASTAPI app imported successfully')"

      - name: Run tests
        run: |
          pytest test_database.py
